name: Publish Release

on:
  workflow_dispatch:
    inputs: 
      version: 
        type: string
        description: 'Release version'
        required: true
  push:
    tags:
      - '*'

jobs:
  windows:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Run Nuke Build
        run: ./.nuke/build.cmd PublishGitHub
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_VERSION: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.version }}