name: Publish Release

on:
  workflow_dispatch:

jobs:
  windows:
    name: windows-2022
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Nuke Build
        run: ./.nuke/build.cmd PublishGitHub PublishNuget
        env:
          NugetApiKey: ${{ secrets.NUGET_APIKEY }}
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}